<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgZgO4u\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgZgO4u/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWgZgO4u.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerWgZgO4u\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerWgZgO4u\srcProdProjectContainer(array(
    'container.build_hash' => 'WgZgO4u',
    'container.build_id' => '0627ec2a',
    'container.build_time' => 1532957552,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgZgO4u');
