<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.czpZ_vG' shared service.

return $this->privates['.service_locator.czpZ_vG'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventDispatcher' => function () {
    return ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService());
}, 'passwordEncoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'));
}, 'tokenGenerator' => function (): \App\Security\TokenGenerator {
    return ($this->privates['App\Security\TokenGenerator'] ?? $this->privates['App\Security\TokenGenerator'] = new \App\Security\TokenGenerator());
}));
