<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGJKT3qF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGJKT3qF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGJKT3qF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGJKT3qF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGJKT3qF\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GJKT3qF',
    'container.build_id' => '08b3bbde',
    'container.build_time' => 1539256109,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGJKT3qF');
